version: "3"

networks:
  frontend:
# 設定backend子網路
  backend:
    ipam:
      driver: default
      config:
        - subnet: ${BACKEND_SUBNET}

services:

# php
  php:
    container_name: php
    networks:
      - backend
    build: ./php/
    expose:
      - 9000
    volumes:
      - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./../:/var/www/html/
    tty: true

# nginx
  nginx:
    container_name: nginx
    networks:
      backend:
        ipv4_address: ${NGINX_IP}
      frontend:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/ssl
      - ./nginx/conf:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx
      - ./../:/var/www/html/

# mariadb
  mariadb-master:
    container_name: mariadb-master
    networks:
      - backend
    build: ./mariadb/master-dockerfile/
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: hypenode
      MYSQL_USER: maria
      MYSQL_PASSWORD: maria
    volumes:
      - ./mariadb/data-master:/var/lib/mysql

  mariadb-slave01:
    container_name: mariadb-slave01
    networks:
      - backend
    build: ./mariadb/slave-dockerfile/
    links:
      - mariadb-master
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: hypenode
      MYSQL_USER: maria
      MYSQL_PASSWORD: maria
    volumes:
      - ./mariadb/data-slave01:/var/lib/mysql

# phpmyadmin
  phpmyadmin:
    container_name: phpmyadmin
    networks:
      - frontend
      - backend
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb-master

# redis
  redis:
    container_name: redis
    networks:
      - backend
    image: redis:3.2
    ports:
      - "6379:6379"